### PR TITLE
Support state change subscription

### PR DESCRIPTION
**Pull request by i-norden**
Needs release with https://github.com/vulcanize/ipld-eth-indexer/pull/81

Ideally we would create a new Postgres trigger to collect and package all of the data required for the payload from inside Postgres (from across the header_cids, state_cids, storage_cids, and IPLD blocks tables), but this implementation uses the current triggers written for Postgraphile to collect the header ID on a new header insert and then round-trips to the DB to collect the payload data from those four tables. 

Still needs test.

### CODE REVIEW

**Comment by AFDudley** [comment]
@yaoandrew  Please review

**Comment by AFDudley** [comment]
This is a feature requested by the 8th light team, but I think it also fits in with our current work around removing postgraphile so I wanted to bring it to @ashwinphatak's attention.

**Comment by yaoandrew** [comment]
> This is a feature requested by the 8th light team, but I think it also fits in with our current work around removing postgraphile so I wanted to bring it to @ashwinphatak's attention.

Hi guys... I'm sorry, I think I may have had a [text] miscommunication with Rick, but if you want to support getting state changes in your stack from our State Diffing node, that's great. We originally thought we could get away from using our fork of geth and utilize the tracing API, but now I don't think that's possible. We plan to continue keeping this fork up to date for the time being.

**Comment by ecmendenhall** [comment]
Appreciate this work! The enhancements y'all have been working on are impressive. I'll pull this and the other dependencies and see if we can plug into this as our statediffing subscription source.

**Pull request closed without merging**
